config/routes.rb
Rails.application.routes.draw do

  root 'welcome#index'
  devise_for :users, :controllers => { registrations: 'registrations' }
  get '/:username/'=> 'internal#index', as: 'internal_page'

   namespace :api, defaults: {format: :json} do
     resources :cats, only: [:index, :create, :destroy, :update]
   end

end

app/models/cat.rb
class Cat < ActiveRecord::Base

end

app/models/character.rb
class Character < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  validates :username, :presence => true, :uniqueness => true

 has_many :characters
end

app/controllers/api/cats_controller.rb
class Api::CatsController < ApplicationController
  before_action :set_cat, only: [:destroy, :update]

  def index
    @cats = Cat.all
    render :index
  end

  def update
    if @cat.update(cat_params)
      render :show
    else
      render json: @cat.errors.fullmessages, status: :unprocessable_entity
    end
  end

  def create
    @cat = Cat.new(cat_params)
    if @cat.save
      render :show
    else
      render json: @cat.errors.fullmessages, status: :unprocessable_entity
    end
  end

  def destroy
    @cat.destroy
  end

  private
  def set_cat
    @cat = Cat.find(params[:id])
  end
  def cat_params
    params.require(:cat).permit(:name, :race).tap do |whitelisted|
      whitelisted[:catClasses] = params[:cat][:catClasses]
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :set_g_user



	def set_g_user
		current_user = User.find_by_email(params[:email])
	end
end

app/controllers/cats_controller.rb
class CatsController < InternalController
  before_action :set_cat, only: [:show, :edit, :update, :destroy]
  respond_to :json, :html
  # GET /cats
  # GET /cats.json
  def index
    @cats = Cat.where(:user_id => current_user.id)
  end

  # GET /cats/1
  # GET /cats/1.json
  def show
  end

  # GET /cats/new
  def new
    @cat = Cat.new
  end

  # GET /cats/1/edit
  def edit
    @cat = Cat.find(params[:id])
  end

  # POST /cats
  # POST /cats.json
  def create
    @cat = Cat.new(cat_params)

    respond_to do |format|
      if @cat.save
        format.html { redirect_to cat_path(current_user.id, @cat), notice: 'Cat was successfully created.' }
        format.json { render :show, status: :created, location: @cat }
      else
        format.html { render :new }
        format.json { render json: @cat.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cats/1
  # PATCH/PUT /cats/1.json
  def update
    respond_to do |format|
      if @cat.update(cat_params)
        format.html { redirect_to cat_path(current_user.id, @cat), notice: 'Cat was successfully updated.' }
        format.json { render :show, status: :ok, location: @cat }
      else
        format.html { render :edit }
        format.json { render json: @cat.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cats/1
  # DELETE /cats/1.json
  def destroy
    @cat.destroy
    respond_to do |format|
      format.html { redirect_to cats_url, notice: 'Cat was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_cat
      @cat = Cat.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def cat_params
      params.require(:cat).permit(:name, :race, :ch_class, :user_id)
    end
end

app/controllers/characters_controller.rb
class CharactersController < ApplicationController
end

app/controllers/internal_controller.rb
class InternalController < ApplicationController
	before_action :authenticate_user!
	before_filter :check_user

	def check_user
		if params[:username] == current_user.username

	      else
		      redirect_to root_path,
	          alert: "This is not your profile."

		end

	end


end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private

  def sign_up_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:username, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	before_filter :redirect_logged_in

	def redirect_logged_in
		if current_user
			redirect_to internal_page_path(current_user.username) 
		end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/helpers/characters_helper.rb
module CharactersHelper
end

app/helpers/internal_helper.rb
module InternalHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/cats/_form.html.erb
<%= form_for :cat, url: cat_path(current_user.id, @cat), method: :patch do |f| %>
  <% if @cat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cat.errors.count, "error") %> prohibited this cat from being saved:</h2>

      <ul>
      <% @cat.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :race %><br>
    <%= f.text_field :race %>
  </div>
  <div class="field">
    <%= f.label :ch_class %><br>
    <%= f.text_field :ch_class, :value => (@cat.ch_class or "").to_json %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.hidden_field :user_id, :readonly => true, :value => current_user.id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cats/_new_form.html.erb
<%= form_for :cat do |f| %>
  <% if @cat.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@cat.errors.count, "error") %> prohibited this cat from being saved:</h2>

      <ul>
      <% @cat.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :race %><br>
    <%= f.text_field :race %>
  </div>
  <div class="field">
    <%= f.label :ch_class %><br>
    <%= f.text_field :ch_class, :value => @cat.ch_class.to_json %>
  </div>
  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.hidden_field :user_id, :readonly => true, :value => current_user.id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cats/edit.html.erb
<h1>Editing Cat</h1>

<%= render 'form' %>

<%= link_to 'Show', cat_path(current_user.username, @cat.id) %> |
<%= link_to 'Back', cats_path %>

app/views/cats/index.html.erb
<h1>Listing Cats</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Race</th>
      <th>Ch class</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cats.each do |cat| %>
      <tr>
        <td><%= cat.name %></td>
        <td><%= cat.race %></td>
        <td><% cat.ch_class.each_with_index do |cls, idx| %>
            <%= cls['ch_class'] %> Level <%= cls['level'] %> <%= idx < cat.ch_class.length - 1  ? "|" : nil %>
            <% end %>
        </td>
         <td><%= cat.user.username %></td>
        <td><%= link_to 'Show', cat_path(current_user.username, cat.id) %></td>
        <td><%= link_to 'Edit', edit_cat_path(current_user.username, cat.id) %></td>
        <td><%= link_to 'Destroy', cat_path(current_user.username, cat.id), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Cat', new_cat_path %>

app/views/cats/new.html.erb
<h1>New Cat</h1>

<%= render 'new_form' %>

<%= link_to 'Back', cats_path %>

app/views/cats/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @cat.name %>
</p>

<p>
  <strong>Race:</strong>
  <%= @cat.race %>
</p>

<p>
  <strong>Ch class:</strong>
  <%= @cat.ch_class %>
</p>

<%= link_to 'Edit', edit_cat_path(current_user.username, @cat.id) %> |
<%= link_to 'Back', cats_path %>

app/views/internal/index.erb
<!--col-66-->
<div id="root"></div>
<!--FOOTER-->
<footer>
<p><span class="excellentorange">GDZ Enterprises</span> Twenty Fifteen</p>
</footer>
<!--FOOTER-->

app/views/layouts/application.html.erb
<!--template for all pages-->
<!DOCTYPE html>
<html lang="en" >
<head>
	<meta charset="UTF-8">
	<title>Cohort - Tabletop RPG GM Companion App</title>


	 <%= stylesheet_link_tag    'application', media: 'all' %>
     <%= javascript_include_tag 'application' %>
     <%= csrf_meta_tags %>
</head>
<body>
<div class="navbar">
		<%= link_to(image_tag('Cohort.PNG', :alt => 'logo'), root_path) %>
	</div>
		<menu>
			<% if user_signed_in? %>
			  Logged in as <strong><%= current_user.email %></strong>.
			  <%= link_to 'Edit profile', edit_user_registration_path %> |
			  <%= link_to "Logout", destroy_user_session_path, method: :delete %>
			<% else %>
			  <%= link_to "Sign up", new_user_registration_path  %> |
			  <%= link_to "Login", new_user_session_path %>
			<% end %>
		</menu>
<% if notice %>
  <p class="notice"><%= notice %></p>
<% end %>
<% if alert %>
  <p class="alert"><%= alert %></p>
<% end %>

<%= yield %><!--ruby that says whatever goes on this page goes here-->

</body>
</html>

app/views/welcome/index.erb


	<div class="col-34">
		<h1>Why, Hello World. Fancy meeting you here!</h1>
		<p class="excellentorange"><strong>This site is definitely under construction right now.</strong></p>
		<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magni repellat quo, sit modi nihil natus, reiciendis impedit aperiam commodi, quos similique id ullam quas ipsum quisquam a consequatur ut dolor?</p>
		
		<%= link_to "Log In", new_user_session_path, class: "button1" %>
        <%= link_to "Sign Up", new_user_registration_path, class: "button2" %>
	</div>

	<div class="col-66">
		<h1>What the Heck is Cohort?</h1>
		<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Magni repellat quo, sit modi nihil natus, reiciendis impedit aperiam commodi, quos similique id ullam quas ipsum quisquam a consequatur ut dolor? </p>
		<ul>
			<li>Open source Dungeon Master's companion app for Pathfinder (for now, more version compatibility to come</li>
			<li>NO AFFILIATION WITH Pathfinder or Wizards or any of that (don't sue us, we're just big ol fans!)</li>
			<li>Currently under devleopment, rolling out new features as fast as we can</li>
		</ul>
		<p>Thanks for checking us out!</p>

		<div class="screenshot-container">

			<div class="screenshot-25">
				<h2><a href="#">Create Campaign</a></h2>
				<img src="#"/>
				<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
				tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
				quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
				consequat.</p>
			</div>

			<div class="screenshot-25">
				<h2><a href="#">Character Sheets</a></h2>
				<img src="#"/>
				<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
				tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
				quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
				consequat.</p>
			</div>

			<div class="screenshot-25">
				<h2><a href="#">DM Interface</a></h2>
				<img src="#"/>
				<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
				tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
				quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
				consequat.</p>
			</div>

		</div><!--screenshot-container-->
	</div><!--col-66-->

	<!--FOOTER-->
	<footer>
	<p><span class="excellentorange">GDZ Enterprises</span> Twenty Fifteen</p>
	</footer>